on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master

jobs:
  build_job:
    runs-on: ubuntu-latest
    name: A job to rebuild contents of main site
    steps:
      # Use the output from the `hello` step
      - name: Trigger deploy for main site
        run: |
          sleep 30
          curl -X POST -d {} ${{ secrets.BUILD_HOOK }}